version: "2"
run:
  allow-parallel-runners: true
linters:
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  default: none
  enable:
    - asciicheck
    - bodyclose
    - bidichk
    - cyclop
    - decorder
    - dogsled
    - errcheck
    - goconst
    - gocritic
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    staticcheck:
      checks: ["all", "-SA5001"]
    funlen:
      lines: 80
      statements: 70
    gosec:
      excludes:
        - G402
    revive:
      rules:
        - name: var-naming
          arguments:
            - - ID
  exclusions:
    generated: lax
    rules:
      - path: _test\.go
        linters:
          - funlen
          - goconst
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
