name: Continuous integration
on:
  push:
    branches:
      - develop
jobs:
  test:
    runs-on: ubuntu-18.04
    services:
      postgres:
        image: postgres:9.6.6-alpine
        env:
          POSTGRES_DB: pgtest
          POSTGRES_USER: pguser
          POSTGRES_PASSWORD: pgdocker
        ports:
          - 5432/tcp
    steps:
      - name: set up golang
        uses: actions/setup-go@v1
        with:
          go-version: 1.11.13
      - name: check out code
        uses: actions/checkout@v1
      - name: unit test
        run: go test -covermode=atomic -coverprofile=profile.cov -v ./...
        env:
          POSTGRES_DB: pgtest
          POSTGRES_USER: pguser
          POSTGRES_PASSWORD: pgdocker
          POSTGRES_HOST: localhost
          POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
          GOPROXY: https://proxy.golang.org
      - name: upload coverage to codecov
        uses: codecov/codecov-action@v1.0.2
        with:
          file: ./profile.cov
          token: ${{ secrets.CODECOV_TOKEN }}
  build:
    needs: test
    runs-on: ubuntu-18.04
    steps:
      - name: set up golang
        uses: actions/setup-go@v1
        with:
          go-version: 1.11.13
      - name: check out code
        uses: actions/checkout@v1
      - name: build docker image
        run: docker build -t dictybase/modware-content:develop-$(git rev-parse --short HEAD) .
      - name: login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: push to docker hub
        run: docker push dictybase/modware-content:develop-$(git rev-parse --short HEAD)
