name: Continuous integration
on:
  push:
    branches:
      - develop
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      arangodb:
        image: arangodb:3.10.9
        env:
          ARANGO_ROOT_PASSWORD: rootpass
        ports:
          - 8529/tcp
    steps:
      - name: set up golang
        uses: actions/setup-go@v4
        with:
          go-version: '~1.20.6'
      - name: check out code
        uses: actions/checkout@v3
      - name: unit test
        run: go test -parallel 4 -covermode=atomic -coverprofile=profile.cov -v ./...
        env:
          ARANGO_USER: root
          ARANGO_PASS: rootpass
          ARANGO_HOST: localhost
          ARANGO_PORT: ${{ job.services.arangodb.ports[8529] }}
          GOPROXY: https://proxy.golang.org
      - name: upload coverage to codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./profile.cov
  call-docker-build:
    needs: test
    uses: dictyBase/workflows/.github/workflows/docker-build-push.yaml@develop
    secrets: inherit
    with:
      repository: ${{ github.repository }}
      ref: ${{ github.ref_name }}
