name: Lint Golang code
on:
  pull_request:
    branches-ignore:
      - master
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: check out code
        uses: actions/checkout@v3
      - name: run linter
        uses: reviewdog/action-golangci-lint@v1
        with:
          github_token: ${{ secrets.github_token }}
          golangci_lint_flags: "-c .golangci.yml"
