name: Lint Golang code
on:
  pull_request:
    branches-ignore:
      - master
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: check out code
        uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: false
      - run: go version
      - name: run linter
        uses: golangci/golangci-lint-action@v3
        with: 
          version: v1.52.2
